name: flutter_hangman
description: Hangman Game

version: 1.2.0+4005

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  moor_flutter: ^1.4.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.0.3
  material_design_icons_flutter: ^3.2.4495
  sqflite: ^1.3.0
  path: ^1.6.4
  flutter_spinkit: ^4.1.2
  date_format: ^1.0.8

dev_dependencies:
  moor_generator: ^1.4.0
  build_runner: ^1.4.0
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/
    - res/
  fonts:
    - family: PatrickHand
      fonts:
        - asset: fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: fonts/FiraMono-Bold.ttf
        - asset: fonts/FiraMono-Regular.ttf